#!/bin/sh

. /Volumes/Data/nfs/zfs-student-5/users/2014/aarouss/Bitnami_MAMP/scripts/setenv.sh

exec /Volumes/Data/nfs/zfs-student-5/users/2014/aarouss/Bitnami_MAMP/php/sbin/.php-fpm.bin -y /Volumes/Data/nfs/zfs-student-5/users/2014/aarouss/Bitnami_MAMP/php/etc/php-fpm.conf -p /Volumes/Data/nfs/zfs-student-5/users/2014/aarouss/Bitnami_MAMP/php/var/ -c /Volumes/Data/nfs/zfs-student-5/users/2014/aarouss/Bitnami_MAMP/php/etc/php.ini "$@"
